spring:
  profiles: dev

  application:
    name: demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dev
    username: admin
    password:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true